#!/usr/bin/env bash
exec &> >(tee -a $HOME/.dotfile-install.log)
set -e
set -x

CONFIGS=("install.conf.yaml")

case $(uname) in
Darwin*)
  CONFIGS+=("mac.conf.yaml")
  ;;
Linux*)
  if [[ -d "$HOME/.config/omarchy" ]]; then
    CONFIGS+=("omarchy.conf.yaml")
  else
    CONFIGS+=("linux.conf.yaml")
  fi
  ;;
esac

CONFIGS+=("after.conf.yaml")

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive --depth 1

for CONFIG in "${CONFIGS[@]}"; do
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
done
