#!/usr/bin/env bash

set -e

CONFIGS=("install.conf.yaml")

case $(uname) in
    Darwin*)
        CONFIGS+=("mac.conf.yaml")
        ;;
    Linux*)
        CONFIGS+=("linux.conf.yaml")
        ;;
esac

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive --depth 1

for CONFIG in ${CONFIGS[@]}; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
done
