enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']
exec-on-workspace-change = [
  '/opt/homebrew/bin/bash',
  '-c',
  '$HOME/.local/bin/aerospace-workspace-change',
]

start-at-login = true

[mode.main.binding]
alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

shift-cmd-h = 'join-with left'
shift-cmd-l = 'join-with right'
shift-cmd-j = 'join-with down'
shift-cmd-k = 'join-with up'

shift-alt-g = ['move left', 'focus up', 'move right']

shift-alt-h = 'move left'
shift-alt-j = 'move down'
shift-alt-k = 'move up'
shift-alt-l = 'move right'

# hyper is cmd-alt-shift-ctrl

cmd-alt-shift-ctrl-f = 'fullscreen'
cmd-alt-shift-ctrl-c = 'reload-config'
cmd-alt-shift-ctrl-space = 'layout floating tiling' # 'floating toggle' in i3
cmd-alt-shift-ctrl-minus = 'resize smart -50'
cmd-alt-shift-ctrl-equal = 'resize smart +50'

# alt-slash = 'layout v_accordion' # 'layout stacking' in i3
# alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'
alt-s = 'workspace S'
alt-p = 'workspace P'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-p = 'move-node-to-workspace P'

alt-r = 'mode resize'
# alt-tab = 'workspace-back-and-forth'
# shift-alt-tab = 'move-workspace-to-monitor --wrap-around next'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
S = 'secondary'
P = 'primary'

[[on-window-detected]]
if.app-id = "com.spotify.client"
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = "com.electron.logseq"
run = 'move-node-to-workspace S'
