# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = uwsm app -- brave --new-window
$webapp = uwsm app -- brave --new-window --ozone-platform=wayland --app

unbind = SUPER SHIFT, J
unbind = SUPER SHIFT, F
unbind = SUPER SHIFT, K
unbind = SUPER, N
unbind = SUPER SHIFT, N
unbind = ALT, TAB

bindd = SUPER, RETURN, Terminal, exec, ghostty --working-directory=$(omarchy-cmd-terminal-cwd)
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser

bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, C, Google Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/calendar/u/0/r"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://betaapp.fastmail.com"
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Notes, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, R, Beeper, exec, uwsm app -- beeper
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"

# Navigation
bindd = SUPER SHIFT, h, Move focus left, movefocus, l
bindd = SUPER SHIFT, l, Move focus right, movefocus, r
bindd = SUPER SHIFT, k, Move focus up, movefocus, u
bindd = SUPER SHIFT, j, Move focus down, movefocus, d

bindd = SUPER SHIFT ALT, h, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT ALT, l, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT ALT, k, Swap window up, swapwindow, u
bindd = SUPER SHIFT ALT, j, Swap window down, swapwindow, d

bindd = SUPER SHIFT, slash, Toggle split, togglesplit,
bindd = SUPER SHIFT, F, Full screen, fullscreen, 1

# Layout controls
bindd = SUPER SHIFT, comma, Master layout, exec, hyprctl keyword general:layout master
bindd = SUPER SHIFT, period, Dwindle layout, exec, hyprctl keyword general:layout dwindle
bindd = SUPER, comma, Cycle layouts, layoutmsg, swapwithmaster master
