---
- hosts: all
  name: manage the system!
  tasks:
      - name: apt repositories
        apt_repository: repo='{{item}}' state=present
        with_items:
            - "deb http://ftp.debian.org/debian/ testing main contrib non-free"
            - "deb http://security.debian.org/ testing/updates main contrib non-free"

      - name: packages
        apt: update_cache=yes cache_valid_time=3600 name={{item}}
        with_items:
          - pulseaudio
          - gnome-screensaver
          - zsh
          - python3.4
          - tmux
          - vim
          - vlc
          - i3
          - apt-file
          - qalculate
          - silversearcher-ag
