---
- hosts: all
  name: manage the system!
  tasks:
      - name: apt pinning preferences
        copy: dest=/etc/apt/preferences.d/pinning src={{DOTFILES}}/apt_pinning

      - name: apt repositories
        apt_repository: repo='{{item}}' state=present
        with_items:
            - "deb http://ftp.debian.org/debian/ testing main contrib non-free"
            - "deb http://security.debian.org/ testing/updates main contrib non-free"
            - "deb http://ftp.debian.org/debian/ unstable main contrib non-free"
            - "deb http://download.virtualbox.org/virtualbox/debian jessie contrib non-free"
            - "deb http://toolbelt.heroku.com/ubuntu ./"
            - "deb http://ppa.launchpad.net/kilian/f.lux/ubuntu trusty main"
            - "deb http://www.deb-multimedia.org testing main non-free"

      - name: packages
        apt: update_cache=yes name={{item}}
        with_items:
          - pulseaudio
          - gnome-screensaver
          - zsh
          - python3.4
          - python3.4-dev
          - python3.4-doc
          - python2.7
          - python2.7-dev
          - python2.7-doc
          - tmux
          - vim
          - vim-gtk  # For X11 clipboard awareness
          - vlc
          - i3
          - apt-file
          - qalculate
          - silversearcher-ag
          - openvpn
          - openssh-server
          - network-manager-openvpn-gnome
          - unzip
          - zip
          - gnupg-agent
          - htop
          - pavucontrol
          - xclip
          - flashplugin-nonfree
          - zlib1g-dev
          - libreadline-dev
          - libbz2-dev
          - libsqlite3-dev
          - libssl-dev
          - awscli
          - pmount
          - libreoffice
          - gdb
          - libmysqlclient-dev
          - lbzip2
          - libffi-dev
          - libxml2-dev
          - libxslt-dev
          - cups-daemon
          - cups
          - printer-driver-hpcups
          - virtualbox
          - mtr
          - darktable
          - gimp
          - pv
          - xbacklight
          - subversion
          - heroku-toolbelt
          - ruby
          - fluxgui
